language: generic

sudo: required

#env:
#  - test: Ubuntu 14.04 Apache
#    distribution: ubuntu
#    version: 14.04
#    init: /sbin/init
#    run_opts: ""

addons:
  hosts:
    - aegir.local.computer
    - sitetest.aegir.local.computer

services:
  - docker

before_script:
  - sudo su -c "echo 'Host git.drupal.org' >> ~/.ssh/config; echo '  StrictHostKeyChecking no' >> ~/.ssh/config "
  - sudo chmod 400 ~/.ssh/config
  - sudo cat ~/.ssh/config
  - sudo ls -la ~/.ssh

script:
  - sudo bash prepare.sh