language: php

sudo: required

# Only run test when committing to a master branch.
branches:
  only:
    - master

#env:
#  - test: Ubuntu 14.04 Apache
#    distribution: ubuntu
#    version: 14.04
#    init: /sbin/init
#    run_opts: ""

addons:
  hosts:
    - aegir.local.computer
    - sitetest.aegir.local.computer

services:
  - docker

before_install:
  - sudo docker --version

  # Install Robo
  - wget https://github.com/consolidation/Robo/releases/download/1.0.5/robo.phar
  - sudo mv robo.phar /usr/local/bin/robo
  - sudo chmod +x /usr/local/bin/robo

  # Install Drush
  - wget https://github.com/drush-ops/drush/releases/download/8.1.9/drush.phar
  - sudo mv drush.phar /usr/local/bin/drush
  - sudo chmod +x /usr/local/bin/drush

  # Prepare devshop CLI and tests
  - composer install
  - composer install -d tests

script:
  # Switch to docker group to run prepare.sh
  - robo up --test --prepare-containers -n