version: '2'

services:

  hostmaster:

    image: aegir/hostmaster:local
    ports:
      - 80:80
    hostname: aegir.local.computer
    links:
      - database
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
    volumes:
      - ./aegir-home:/var/aegir

  database:
    image: mariadb
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
    # Optionally keep the mysql db files in an accessible directory.
    #volumes:
    #  - ./aegir-db:/var/lib/mysql

    # These options are needed for Drupal 7.50 and up for full UTF-8 support.
    # See https://www.drupal.org/node/2754539
    command: mysqld --innodb-large-prefix --innodb-file-format=barracuda --innodb-file-per-table

phpmyadmin:
  ports:
  - 808:80
  environment:
    MYSQL_ROOT_PASSWORD: longrandomsecurepassword
  tty: true
  image: phpmyadmin/phpmyadmin
  links:
  - database:db
  stdin_open: true