version: '2'

services:
#  load:
#    image: tutum/haproxy
#    links:
#        - hostmaster
#    ports:
#      - 80:80
#    restart: always
#    depends_on:
#      - hostmaster
  hostmaster:
    privileged: true
    image: aegir/hostmaster:privileged
    ports:
      - 80:80
    hostname: aegir.local.computer
    links:
      - database
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword

      # To Test Hosting Docker, Provision needs to know what your host machine's aegir-home path is, so it can write volume paths.
      HOST_AEGIR_HOME: /home/jon/Projects/aegir/aegir-home
      AEGIR_VERSION: 7.x-3.x
      AEGIR_MAKEFILE: /var/aegir-dev.make
      AEGIR_HOSTMASTER_ROOT: /var/aegir/hostmaster-7.x-3.x
    volumes:
      - ./aegir-home:/var/aegir:Z
      - ./aegir-dev.make:/var/aegir-dev.make:Z
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    image: mariadb
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
    # Optionally keep the mysql db files in an accessible directory.
    #volumes:
    #  - ./aegir-db:/var/lib/mysql

    # These options are needed for Drupal 7.50 and up for full UTF-8 support.
    # See https://www.drupal.org/node/2754539
    command: mysqld --innodb-large-prefix --innodb-file-format=barracuda --innodb-file-per-table

  phpmyadmin:
    ports:
    - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: longrandomsecurepassword
    tty: true
    image: phpmyadmin/phpmyadmin
    links:
    - database:db
    stdin_open: true