load:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
hostmaster:
  scale: 1
database:
  scale: 1
phpmyadmin:
  scale: 1